[app]
language=en

[cisSubscriber]
port=48478
version="2.3CZ1.0"
serviceName="CustomerInformationService"
serviceType="_ibisip_http._tcp"
;structure="CurrentDisplayContent"
structure="AllData"
;replyPath=/xxx


